### ISSUE TITLE
weekly quests review

### ISSUE THREAD

**Issue by MrGrohminet** [Apero-Online/apero#135]
Easy : 1Mexp - lvl min 40
Medium : 5Mexp - lvl min 70
Hard : 25Mexp - lvl min 90
```
  - Id: 91000
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: ALLIGATOR
          Count: 100
  - Id: 91001
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: ANTIQUE_FIRELOCK
          Count: 100
  - Id: 91002
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: CARAT
          Count: 100
  - Id: 91003
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: CRUISER
          Count: 100
  - Id: 91004
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: GARGOYLE
          Count: 100
  - Id: 91005
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: GREATEST_GENERAL
          Count: 100
  - Id: 91006
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: LES
          Count: 100
  - Id: 91007
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: MARC
          Count: 100
  - Id: 91008
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: SPORE ->>> a changer après la quête de cette semaine
          Count: 100
  - Id: 91009
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: MARDUK
          Count: 100
  - Id: 91010
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: NIGHTMARE
          Count: 100
  - Id: 91011
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: PITMAN
          Count: 100
  - Id: 91012
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: STONE_SHOOTER
          Count: 100
  - Id: 91013
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: WILD_ROSE
          Count: 100
  - Id: 91014
    Title: Chasse Hebdomadaire - Facile
    Targets:
        - Mob: ZENORC
          Count: 100
## Moyen
  - Id: 91000
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: ALARM
          Count: 150
  - Id: 91101
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: ASSULTER
          Count: 150
  - Id: 91102
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: GEOGRAPHER --->> a changer après la quête de cette semaine
          Count: 150
  - Id: 91103
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: VAVAYAGA
          Count: 150
  - Id: 91104
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: BAPHOMET_
          Count: 150
  - Id: 91105
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: DARK_FRAME
          Count: 150
  - Id: 91106
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: FLAME_SKULL
          Count: 150
  - Id: 91107
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: GAZETI
          Count: 150
  - Id: 91108
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: GOAT
          Count: 150
  - Id: 91109
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: HYLOZOIST
          Count: 150
  - Id: 91110
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: KAPHA
          Count: 150
  - Id: 91111
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: KNOCKER
          Count: 150
  - Id: 91112
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: CIVIL_SERVANT
          Count: 150
  - Id: 91113
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: SKEL_PRISONER
          Count: 150
  - Id: 91114
    Title: Chasse Hebdomadaire - Moyen
    Targets:
        - Mob: TEDDY_BEAR
          Count: 150
## Difficile
  - Id: 91200
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: RAGGED_ZOMBIE
          Count: 200
  - Id: 91201
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: ACIDUS
          Count: 200
  - Id: 91202
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: AGAV
          Count: 200
  - Id: 91203
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: ALIOT
          Count: 200
  - Id: 91204
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: ANCIENT_MUMMY
          Count: 200
  - Id: 91205
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: APOCALIPS
          Count: 200
  - Id: 91206
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: BANSHEE
          Count: 200
  - Id: 91207
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: ECHIO
          Count: 200
  - Id: 91208
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: FRUS
          Count: 200
  - Id: 91209
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: GALION
          Count: 200
  - Id: 91210
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: ICE_TITAN
          Count: 200
  - Id: 91211
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: LAVA_GOLEM
          Count: 200
  - Id: 91212
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: MEDUSA
          Count: 200
  - Id: 91213
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: NIGHTMARE_TERROR
          Count: 200
  - Id: 91214
    Title: Chasse Hebdomadaire - Difficile
    Targets:
        - Mob: OWL_DUKE
          Count: 200
```
